import { Phase, Document } from '../types';

export const journeyPhases: Phase[] = [
  {
    id: 'phase-1',
    number: 1,
    title: 'Research & Planning',
    description: 'Research universities, countries, and create your initial plan',
    timeframe: '12-18 months before departure',
    status: 'completed',
    icon: '🔍',
    tasks: [
      {
        id: 'task-1-1',
        title: 'Research top universities in target country',
        description: 'Create a list of 8-10 universities that match your goals',
        completed: true,
        priority: 'High',
        category: 'Research',
      },
      {
        id: 'task-1-2',
        title: 'Check entry requirements for each program',
        description: 'Review GPA, test scores, and other requirements',
        completed: true,
        priority: 'High',
        category: 'Research',
      },
      {
        id: 'task-1-3',
        title: 'Compare cost of living in different cities',
        description: 'Use STAB comparison tool to evaluate expenses',
        completed: true,
        priority: 'Medium',
        category: 'Research',
      },
      {
        id: 'task-1-4',
        title: 'Research visa requirements',
        description: 'Understand visa process for your target country',
        completed: true,
        priority: 'High',
        category: 'Research',
      },
      {
        id: 'task-1-5',
        title: 'Calculate total budget needed',
        description: 'Include tuition, living costs, travel, and emergency funds',
        completed: true,
        priority: 'High',
        category: 'Financial',
      },
      {
        id: 'task-1-6',
        title: 'Join student forums and communities',
        description: 'Connect with current students in your target universities',
        completed: false,
        priority: 'Low',
        category: 'Networking',
      },
      {
        id: 'task-1-7',
        title: 'Attend virtual university fairs',
        description: 'Get information directly from university representatives',
        completed: false,
        priority: 'Medium',
        category: 'Networking',
      },
      {
        id: 'task-1-8',
        title: 'Request official transcripts',
        description: 'Order transcripts from your current/previous institutions',
        completed: true,
        priority: 'High',
        category: 'Documents',
      },
    ],
  },
  {
    id: 'phase-2',
    number: 2,
    title: 'Standardized Tests',
    description: 'Prepare for and take required English and entrance exams',
    timeframe: '9-12 months before departure',
    status: 'in-progress',
    icon: '📝',
    tasks: [
      {
        id: 'task-2-1',
        title: 'Choose English proficiency test (IELTS/TOEFL)',
        description: 'Check which test is accepted by your universities',
        completed: true,
        priority: 'High',
        category: 'Tests',
      },
      {
        id: 'task-2-2',
        title: 'Register for English proficiency test',
        description: 'Book your test date 2-3 months in advance',
        completed: true,
        priority: 'High',
        category: 'Tests',
      },
      {
        id: 'task-2-3',
        title: 'Take practice tests',
        description: 'Complete at least 3-5 full practice tests',
        completed: false,
        priority: 'High',
        category: 'Tests',
      },
      {
        id: 'task-2-4',
        title: 'Take official English proficiency exam',
        description: 'Aim for score above university minimum requirements',
        completed: false,
        priority: 'High',
        category: 'Tests',
      },
      {
        id: 'task-2-5',
        title: 'Check if GRE/GMAT required',
        description: 'Some graduate programs require additional tests',
        completed: true,
        priority: 'Medium',
        category: 'Tests',
      },
      {
        id: 'task-2-6',
        title: 'Send test scores to universities',
        description: 'Most tests allow free score reports to 4-5 universities',
        completed: false,
        priority: 'High',
        category: 'Tests',
      },
    ],
  },
  {
    id: 'phase-3',
    number: 3,
    title: 'Applications',
    description: 'Prepare documents and submit applications to universities',
    timeframe: '6-9 months before departure',
    status: 'not-started',
    icon: '📄',
    tasks: [
      {
        id: 'task-3-1',
        title: 'Write Statement of Purpose (SOP)',
        description: 'Explain your academic goals and why you want to study there',
        completed: false,
        priority: 'High',
        category: 'Documents',
      },
      {
        id: 'task-3-2',
        title: 'Prepare CV/Resume',
        description: 'Highlight academic achievements, work experience, and skills',
        completed: false,
        priority: 'High',
        category: 'Documents',
      },
      {
        id: 'task-3-3',
        title: 'Request 2-3 recommendation letters',
        description: 'Ask professors or supervisors who know you well',
        completed: false,
        priority: 'High',
        category: 'Documents',
      },
      {
        id: 'task-3-4',
        title: 'Translate documents if needed',
        description: 'Get certified translations of non-English documents',
        completed: false,
        priority: 'Medium',
        category: 'Documents',
      },
      {
        id: 'task-3-5',
        title: 'Create accounts on university portals',
        description: 'Set up application accounts for each university',
        completed: false,
        priority: 'High',
        category: 'Application',
      },
      {
        id: 'task-3-6',
        title: 'Fill out application forms',
        description: 'Complete all sections carefully and accurately',
        completed: false,
        priority: 'High',
        category: 'Application',
      },
      {
        id: 'task-3-7',
        title: 'Pay application fees',
        description: 'Application fees typically range from $50-150 per university',
        completed: false,
        priority: 'High',
        category: 'Application',
      },
      {
        id: 'task-3-8',
        title: 'Submit applications before deadlines',
        description: 'Submit at least 1 week before deadline to avoid issues',
        completed: false,
        priority: 'High',
        category: 'Application',
      },
      {
        id: 'task-3-9',
        title: 'Track application status',
        description: 'Check email and portals regularly for updates',
        completed: false,
        priority: 'Medium',
        category: 'Application',
      },
    ],
  },
  {
    id: 'phase-4',
    number: 4,
    title: 'Financial Planning',
    description: 'Apply for scholarships and arrange funding',
    timeframe: '6-9 months before departure',
    status: 'not-started',
    icon: '💰',
    tasks: [
      {
        id: 'task-4-1',
        title: 'Research available scholarships',
        description: 'Use STAB scholarship database to find opportunities',
        completed: false,
        priority: 'High',
        category: 'Scholarships',
      },
      {
        id: 'task-4-2',
        title: 'Shortlist 10-15 scholarships',
        description: 'Focus on scholarships you are eligible for',
        completed: false,
        priority: 'High',
        category: 'Scholarships',
      },
      {
        id: 'task-4-3',
        title: 'Prepare scholarship essays',
        description: 'Write compelling essays explaining your financial need and goals',
        completed: false,
        priority: 'High',
        category: 'Scholarships',
      },
      {
        id: 'task-4-4',
        title: 'Apply for scholarships',
        description: 'Submit applications before deadlines',
        completed: false,
        priority: 'High',
        category: 'Scholarships',
      },
      {
        id: 'task-4-5',
        title: 'Open international bank account',
        description: 'Set up account that works in your target country',
        completed: false,
        priority: 'Medium',
        category: 'Banking',
      },
      {
        id: 'task-4-6',
        title: 'Prepare bank statements',
        description: 'Collect last 6 months of bank statements for visa',
        completed: false,
        priority: 'High',
        category: 'Banking',
      },
      {
        id: 'task-4-7',
        title: 'Get sponsor/parent financial documents',
        description: 'If someone is sponsoring your studies',
        completed: false,
        priority: 'High',
        category: 'Banking',
      },
      {
        id: 'task-4-8',
        title: 'Create monthly savings plan',
        description: 'Track progress toward your funding goal',
        completed: false,
        priority: 'Medium',
        category: 'Banking',
      },
    ],
  },
  {
    id: 'phase-5',
    number: 5,
    title: 'Visa & Documentation',
    description: 'Apply for student visa and prepare legal documents',
    timeframe: '3-6 months before departure',
    status: 'locked',
    icon: '🛂',
    tasks: [
      {
        id: 'task-5-1',
        title: 'Receive university acceptance letter',
        description: 'Get official acceptance from at least one university',
        completed: false,
        priority: 'High',
        category: 'Visa',
      },
      {
        id: 'task-5-2',
        title: 'Pay tuition deposit',
        description: 'Secure your spot by paying deposit to university',
        completed: false,
        priority: 'High',
        category: 'Visa',
      },
      {
        id: 'task-5-3',
        title: 'Get CAS/I-20/CoE letter',
        description: 'Receive visa support letter from university',
        completed: false,
        priority: 'High',
        category: 'Visa',
      },
      {
        id: 'task-5-4',
        title: 'Collect all visa documents',
        description: 'Prepare passport, photos, financial docs, acceptance letter',
        completed: false,
        priority: 'High',
        category: 'Visa',
      },
      {
        id: 'task-5-5',
        title: 'Book visa appointment',
        description: 'Schedule appointment at embassy/visa center',
        completed: false,
        priority: 'High',
        category: 'Visa',
      },
      {
        id: 'task-5-6',
        title: 'Pay visa application fee',
        description: 'Fees vary by country ($160-500)',
        completed: false,
        priority: 'High',
        category: 'Visa',
      },
      {
        id: 'task-5-7',
        title: 'Attend visa interview/biometrics',
        description: 'Be prepared to answer questions about your study plans',
        completed: false,
        priority: 'High',
        category: 'Visa',
      },
      {
        id: 'task-5-8',
        title: 'Get medical examination',
        description: 'Some countries require health check-ups',
        completed: false,
        priority: 'Medium',
        category: 'Health',
      },
      {
        id: 'task-5-9',
        title: 'Get required vaccinations',
        description: 'Check vaccination requirements for your destination',
        completed: false,
        priority: 'Medium',
        category: 'Health',
      },
      {
        id: 'task-5-10',
        title: 'Receive visa approval',
        description: 'Track your visa application status',
        completed: false,
        priority: 'High',
        category: 'Visa',
      },
    ],
  },
  {
    id: 'phase-6',
    number: 6,
    title: 'Pre-Departure',
    description: 'Book travel, arrange accommodation, and prepare to leave',
    timeframe: '1-3 months before departure',
    status: 'locked',
    icon: '✈️',
    tasks: [
      {
        id: 'task-6-1',
        title: 'Apply for student accommodation',
        description: 'Apply for university dorms or find private housing',
        completed: false,
        priority: 'High',
        category: 'Accommodation',
      },
      {
        id: 'task-6-2',
        title: 'Book flight tickets',
        description: 'Book 3-4 weeks before departure for better prices',
        completed: false,
        priority: 'High',
        category: 'Travel',
      },
      {
        id: 'task-6-3',
        title: 'Get travel insurance',
        description: 'Cover medical emergencies and trip cancellations',
        completed: false,
        priority: 'High',
        category: 'Travel',
      },
      {
        id: 'task-6-4',
        title: 'Purchase student health insurance',
        description: 'Many universities require proof of health insurance',
        completed: false,
        priority: 'High',
        category: 'Health',
      },
      {
        id: 'task-6-5',
        title: 'Arrange airport pickup',
        description: 'Book taxi or arrange university pickup service',
        completed: false,
        priority: 'Medium',
        category: 'Travel',
      },
      {
        id: 'task-6-6',
        title: 'Join university student groups',
        description: 'Connect with other incoming students on social media',
        completed: false,
        priority: 'Low',
        category: 'Networking',
      },
      {
        id: 'task-6-7',
        title: 'Pack essentials',
        description: 'Make checklist: documents, clothes, adapters, medications',
        completed: false,
        priority: 'Medium',
        category: 'Preparation',
      },
      {
        id: 'task-6-8',
        title: 'Get international SIM card or plan',
        description: 'Ensure you have connectivity upon arrival',
        completed: false,
        priority: 'Medium',
        category: 'Preparation',
      },
      {
        id: 'task-6-9',
        title: 'Exchange currency',
        description: 'Get some local currency for initial expenses',
        completed: false,
        priority: 'Medium',
        category: 'Preparation',
      },
      {
        id: 'task-6-10',
        title: 'Attend pre-departure orientation',
        description: 'Join university orientation sessions if available',
        completed: false,
        priority: 'Low',
        category: 'Preparation',
      },
    ],
  },
];

export const documentsList: Document[] = [
  {
    id: 'doc-1',
    name: 'Passport',
    category: 'Personal',
    status: 'ready',
    required: true,
    expiryDate: new Date('2030-06-15'),
  },
  {
    id: 'doc-2',
    name: 'Passport Photos',
    category: 'Personal',
    status: 'ready',
    required: true,
  },
  {
    id: 'doc-3',
    name: 'Birth Certificate',
    category: 'Personal',
    status: 'in-progress',
    required: true,
  },
  {
    id: 'doc-4',
    name: 'High School Diploma',
    category: 'Academic',
    status: 'ready',
    required: true,
  },
  {
    id: 'doc-5',
    name: 'University Transcripts',
    category: 'Academic',
    status: 'ready',
    required: true,
  },
  {
    id: 'doc-6',
    name: 'Degree Certificate',
    category: 'Academic',
    status: 'ready',
    required: true,
  },
  {
    id: 'doc-7',
    name: 'Translated Transcripts',
    category: 'Academic',
    status: 'in-progress',
    required: false,
  },
  {
    id: 'doc-8',
    name: 'English Test Score (IELTS/TOEFL)',
    category: 'Tests',
    status: 'missing',
    required: true,
  },
  {
    id: 'doc-9',
    name: 'GRE/GMAT Score',
    category: 'Tests',
    status: 'missing',
    required: false,
  },
  {
    id: 'doc-10',
    name: 'Statement of Purpose',
    category: 'Application',
    status: 'missing',
    required: true,
  },
  {
    id: 'doc-11',
    name: 'CV/Resume',
    category: 'Application',
    status: 'in-progress',
    required: true,
  },
  {
    id: 'doc-12',
    name: 'Recommendation Letters',
    category: 'Application',
    status: 'missing',
    required: true,
  },
  {
    id: 'doc-13',
    name: 'Bank Statements',
    category: 'Financial',
    status: 'missing',
    required: true,
  },
  {
    id: 'doc-14',
    name: 'Sponsor Letter',
    category: 'Financial',
    status: 'missing',
    required: false,
  },
  {
    id: 'doc-15',
    name: 'Scholarship Award Letter',
    category: 'Financial',
    status: 'missing',
    required: false,
  },
];

export function calculateOverallProgress(phases: Phase[]): number {
  let totalTasks = 0;
  let completedTasks = 0;

  phases.forEach((phase) => {
    phase.tasks.forEach((task) => {
      totalTasks++;
      if (task.completed) {
        completedTasks++;
      }
    });
  });

  return totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;
}

export function getPhaseProgress(phase: Phase): number {
  const totalTasks = phase.tasks.length;
  const completedTasks = phase.tasks.filter((task) => task.completed).length;
  return totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;
}

export function getDaysUntilDate(targetDate: Date): number {
  const now = new Date();
  const diffInMs = targetDate.getTime() - now.getTime();
  return Math.ceil(diffInMs / (1000 * 60 * 60 * 24));
}
